
cache:
    directories:
        - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            os: 'linux'
            dist: 'trusty'
            sudo: false
            language: 'php'
            php: '7.1'
        -
            os: 'linux'
            dist: 'trusty'
            sudo: false
            language: 'php'
            php: '7.2'

before_install:
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'

install:
    - 'composer install --no-progress'

script:
    - 'bin/robo lint'
    - 'bin/robo test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
